### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by a-type** [a-type/gnocchi#125]
Getting the onboarding details right / not embarrassing myself too much

- [x] Check PWA icon on iPhone
- [x] Add recipes and upgrade features to homepage
- [ ] Add a PH banner?
- [x] Make sure payment flow still works
- [x] Make a promo video with voiceover
- [x] Make a Twitter
- [x] #131 
- [x] Create a launch discount coupon
- [x] Make more PH gallery images showcasing...
- [x] Sync
- [x] Collaboration
- [x] Recipes
- [x] Pantry
- [x] https://github.com/a-type/gnocchi/issues/144
